ARG BASE_IMAGE=ucsctreehouse/care:0.17.0.0
FROM $BASE_IMAGE

# Add to Treehouse group so no need to run as user/group
USER root
RUN groupadd -g 604 treehouse ;  adduser jovyan treehouse

USER jovyan

ADD . /app

WORKDIR /work/outputs
# Put back the original jupyter entrypoint
ENTRYPOINT ["tini", "--", "start-notebook.sh"]
